### ISSUE TITLE
[Suggestion] "Post" Map Configs

### ISSUE THREAD

**Issue by MAGNAT2645** [nosoop/SM-YetAnotherMapConfigPlugin#1]
Could you add [OnConfigsExecuted](https://www.sourcemod.net/new-api/sourcemod/OnConfigsExecuted) support?
So there would be two subfolders in `mapconfigs/`: `pre` (for [OnAutoConfigsBuffered](https://www.sourcemod.net/new-api/sourcemod/OnAutoConfigsBuffered)) and `post` (for [OnConfigsExecuted](https://www.sourcemod.net/new-api/sourcemod/OnConfigsExecuted))
For example:
- `mapconfigs/`
  * `pre/`
    * `all.cfg`,
    * `gametype/`,
    * `maps/`,
    * `workshop/`
  * `post/`
    * `all.cfg`,
    * `gametype/`,
    * `maps/`,
    * `workshop/`

**Comment by nosoop** [comment]
Is there a specific use case? Plugins should only be reading convar changes in `OnConfigsExecuted`, so I don't see any reason to add a post-style callback (which would also fire in an indeterminate order relative to other plugins listening to that forward).  This kind of feature would require an extensive rework of the plugin for seemingly little gain too.

You may be better served by writing a small plugin that adds a `defer` server command to internally buffer commands to be executed in `OnConfigsExecuted`; I think it would be significantly more flexible.

**Comment by MAGNAT2645** [comment]
I don't really remember why but i changed `OnAutoConfigsBuffered` to `OnConfigsExecuted` in [MapConfigs with prefix support](https://github.com/bcserv/mapconfigs).
Maybe due to SteamWorks Game Description overriding so gamemode's descriptions (some gamemodes/plugins don't have convars to disable description overriding) always changes to my own text.
Also i use mapconfigs to unload some plugins which aren't needed on specific gamemode/map.

**Comment by nosoop** [comment]
Yeah; that sounds like a number of badly behaving / resetting plugins.

Part of it might be due to SteamWorks' design of letting natives set descriptions instead of having a forward that lets plugins modify a buffer that gets passed back.  But that's a rant for a different repo.

[I just wrote up an implementation of `defer` here](https://github.com/nosoop/SM-ServerCmdDefer); you may want to try that and see if it works for your particular use case.  A post-style config system seems way out of scope for this project unfortunately.
